project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "ME 2801 — Controls Engineering"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
